const builderSettingsData = {
    display_settings: {
        show_selected_item_in_footer: false,
        enable_image_lightbox: false,
        show_price_button: false,
        show_formated_description: false,
        hide_soldout_products: false,
        show_message_when_adding_to_cart: false,
        add_button_text: "",
        remember_selections: false,
        show_image_carousels: false,
        show_step_progress: false
    },
    style_settings: {
        primary_button_color: "#000",
        secondary_button_color: "#000",
        product_select_color: "#000",
        product_border_color: "#000",
        lightbox_background_color: "#000",
        lightbox_text_color: "#000",
        progress_bar_text_color: "#000",
        progress_bar_color: "#000",
        total_box_background_color: "#000",
        total_text_color: "#000",
        total_price_text_color: "#000",
        order_detail_product_text_color: "#000",
        adding_to_cart_popup_background_color: "#000",
        adding_to_cart_popup_title_color: "#000",
        adding_to_cart_popup_text_color: "#000"
    },
    seo_settings: {
        title: "",
        keywords: "",
        description: ""
    },
    shipping_and_fulfillment: {
        fulfilment_service: "",
        require_shipping: false
    },
    deleted_at: "2022-06-14",
    is_deleted: false,
    builder_name: "",
    live: false,
    charge_tax: false,
    redirect: "",
    use_fixed_price: false,
    fixed_price: 0,
    start_price: 0,
    product_orders: false,
    keep_builder: false,
    theme: {
        full_width_with_fixed_bottom: true,
        fixed_right_side_with_scroll: false
    },
    custom_url_path: "",
    step: 1
}
export const stepsFormData = {
    meta_settings: {
        requied_steps: true,
        show_box_content_summary: true,
        hide_from_step_progress: true,
        show_each_variant_seperately: true,
        show_variant_select_box_beneath_product: true,
        show_sort_by_dropdown_menu: true,
        show_title_filter: true,
        show_collection_filter: true,
        show_tags_filter: true,
        products_per_row: 0,
        set_collection_filter: 0,
        tags: ""
    },
    title: "",
    description: "",
    short_title: "",
    display_order: 0,
    minimum_selection: 0,
    maximum_selection: 0,
    collection: 0,
    type: "string",
    builder_setting: "4"
}

export const dicountFormData = {
    title: "",
    type: "",
    value: 0,
    discount_criteria: "",
    apply_to: "",
    items_required: 0,
    remove_previous_discounts: false,
    encourage_when: 0,
    encourage_discount: false,
    remove_previous_discounts: false,
    order: 0,
    builder_settings: "1",
}


export const language = [

    'Arabic-Tunisia' ,
      'Arabic'   ,
      'Azerbaijani'  ,
      'Bulgarian'   ,
      'Bamanankan',
      'Bengali (Bangla)' ,
      'Breton',
      'Bosnian' ,
      'Catalan',
      'Czech',
      'Welsh',
      'Danish',
      'German',
      'Greek',
      'Australian',
      ' English',
      'Canadian',
      'British/US English',
      'Irish English',
      'New Zealand English',
      'South African English',
      'Esperanto',
      'Spanish',
      'Estonian',
      'Basque',
      'Persian',
      'Finnish',
      'Faroese',
      'French (Switzerland)',
      'French',
      'Galician',
      'Hebrew',
      'Hindi',
      'Croatian',
      'Hungarian',
      'Armenian',
      'Bahasa',
      'Icelandic',
      'Italian (Switzerland)',
      'Italian',
      'Japanese',
      'Georgian',
      'Kazakh',
      'Khmer',
      'Korean',
      'Lithuanian',
      'Latvian',
      'Montenegrin',
      'Macedonian',
      'Mongolian',
       'Marathi',
       'Malay',
       'Belgium-Dutch',
       'Dutch',
       'Norwegian',
       'Occitan',
       'Polish',
       'Brazilian',
       'Portuguese',
       'Romanian',
       'Russian',
       'Sinhala',
       'Slovak',
       'Slovene',
       'Albanian',
       'Serbian latin',
       'Serbian cyrillic',
       'Swedish',
       'Swahili',
       'Tamil',
       'Tajik',
       'Thai',
       'Turkmen',
       'Turkish',
        'Ukrainian',
        'Uzbek cyrillic',
        'Uzbek latin',
        'Vietnamese',
        'Simplified Chinese',
        'Traditional Chinese'  
    ]

    export const weekDays = [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday'
    ]

export default builderSettingsData